### ISSUE TITLE
Off-by-one error in “discuss” preload params

### ISSUE THREAD

**Issue by lucaswerkmeister** [Wikidata/editgroups#112]
There seems to be an off-by-one error in how the “discuss” link preloads the template with the relevant parameters. On [a random edit group](https://editgroups.toolforge.org/b/wikibase-cli/2b321c518841d/), clicking “discuss” preloads the following wikitext:

```
{{Edit group
|uid=wikibase-cli/2b321c518841d
|summary=
|author=replacing bs-language descriptions
|nb_edits=MDanielsBot
|example_page=477220
|oldrevid=Q10720164
|newrevid=2181279353
}}
===Discussion===

{{Ping|replacing bs-language descriptions}} <!-- start the discussion about this edit group here -->
```
Preview:
![image](https://github.com/Wikidata/editgroups/assets/2346599/645b5145-c444-4168-80f6-7a4563700f64)

I assume it’s meant to look like this:
```
{{Edit group
|uid=wikibase-cli/2b321c518841d
|summary=replacing bs-language descriptions
|author=MDanielsBot
|nb_edits=477220
|example_page=Q10720164
|oldrevid=2181279353
|newrevid=2181399728
}}
===Discussion===

{{Ping|MDanielsBot}} <!-- start the discussion about this edit group here -->
```
![image](https://github.com/Wikidata/editgroups/assets/2346599/5446b1d7-b428-4ffe-bb05-0914bef149ee)

(Note: It’s possible that the bug is actually in the template rather than the tool, I don’t know.)

**Comment by wetneb** [comment]
Thanks for reporting! It's curious, I don't seem to be able to reproduce it. When I go to your example page, the "Discuss" link is for me:
https://www.wikidata.org/w/index.php?action=edit&preload=Wikidata%3AEdit_groups/Preload&title=Wikidata%3AEdit_groups/wikibase-cli/2b321c518841d&preloadparams%5b0%5d=wikibase-cli/2b321c518841d&preloadparams%5b2%5d=replacing%20bs-language%20descriptions&preloadparams%5b3%5d=MDanielsBot&preloadparams%5b4%5d=489780&preloadparams%5b5%5d=Q11100318&preloadparams%5b6%5d=1911834475&preloadparams%5b7%5d=2181480854

which generates the following:
```
{{Edit group
|uid=wikibase-cli/2b321c518841d
|summary=replacing bs-language descriptions
|author=MDanielsBot
|nb_edits=489780
|example_page=Q11100318
|oldrevid=1911834475
|newrevid=2181480854
}}
===Discussion===

{{Ping|MDanielsBot}} <!-- start the discussion about this edit group here -->
```

which looks good… I tried a few other ones and it also worked. I also tried while being logged in / logged out of EditGroups / Wikidata and it doesn't seem to make a difference. The preload template hasn't been edited recently either. Could it be that you went through some log-in process as you clicked on the "Discuss" link, which could perhaps mess-up the preload parameters on MediaWiki's side? (I'm not sure how to trigger that as I go directly in anonymous editing mode on my side)

**Comment by lucaswerkmeister** [comment]
Hm, that’s odd… I don’t think there was any login flow on my end. Also, if I follow your link, it also gives me the shifted outcome.

I wonder if it’s a difference between visual editor and non-visual editor? When I follow that link, it puts me in VE’s source editing mode; how about you?

**Comment by lucaswerkmeister** [comment]
Aha, it must be that! If I change the URL to have `action=submit` (old trick to get the old wikitext editor), there’s the right wikitext in there.

So this is presumably… affecting any preloaded template, for a vast number of Wikimedians? :scream:

**Comment by lucaswerkmeister** [comment]
Though I wonder if it’s a general `preloadparams` issue in VE, or potentially related to the fact that the URL here apparently has `&preloadparams[0]=`, `&preloadparams[2]=`, `&preloadparams[3]=`, etc., i.e. skipping `[1]`.

**Comment by lucaswerkmeister** [comment]
Reported at https://phabricator.wikimedia.org/T367671; not actually EditGroups’ fault. Thanks for looking into it!

**Comment by lucaswerkmeister** [comment]
(Though I guess you could work around it by shifting the indexes in [batch.html](https://github.com/Wikidata/editgroups/blob/b43eb44c21b70bd7e639c1c4daf6a07cb107bac6/store/templates/store/batch.html#L100), if you want.)

**Comment by wetneb** [comment]
Ah I hadn't noticed the gap in indices - that's definitely something that I could fix

**Comment by lucaswerkmeister** [comment]
Yup, now it’s working for me – thank you!
