### ISSUE TITLE
Latest edits list does not include latest edits

### ISSUE THREAD

**Issue by Daniel-Mietchen** [Wikidata/editgroups#12]
The batch at 
https://tools.wmflabs.org/editgroups/b/QSv2T/1535570936835/
currently displays its most recent edit as being from September 6, when the batch is still actively being worked on and triggering edits (e.g. [this one](https://www.wikidata.org/w/index.php?title=Q56557325&diff=prev&oldid=743803443&diffmode=source) from today).

Not sure whether this is the same problem as in #6, so opening a separate ticket for the moment.

**Comment by wetneb** [comment]
Thanks for reporting! I will look into this.

**Comment by wetneb** [comment]
This is due to Magnus' recent change of format for QuickStatements batches.
I have reported the problem here:
https://www.wikidata.org/wiki/Topic:Uk6mhn9qnx0vxm6p
