### ISSUE TITLE
Calculation error in "Existing entities edited"

### ISSUE THREAD

**Issue by Daniel-Mietchen** [Wikidata/editgroups#16]
E.g. in
https://tools.wmflabs.org/editgroups/b/QSv2T/1545051844705/ ,
the "-4822" seems unrealistic and looks more like an overflow error.

**Comment by Daniel-Mietchen** [comment]
Similar case in https://tools.wmflabs.org/editgroups/b/QSv2T/1550163252173/ :
> Existing entities edited | -1607

**Comment by wetneb** [comment]
That's likely due to new edits being counted twice.
