### ISSUE TITLE
Is it useful/required to set EditGroup tags from WDTK ?

### ISSUE THREAD

**Issue by tfrancart** [Wikidata/editgroups#34]
As a developper of a bot, do I need to make anything special with edit tags so that the batches are properly categirized in EditGroups ? (https://editgroups.readthedocs.io/en/latest/tagging.html#possible-tags)

I am refering to the 5th parameter of wbde.updateStatements in wdtk :+1: 

```
wbde.updateStatements(
				entityId,
				// statements to add
				statementsAsList,
				// statements to delete
				Collections.emptyList(),
				// summary
				this.editSummary,
				// tags
				Collections.emptyList()
		);
```

How should this parameter be used ?

Thanks

**Comment by wetneb** [comment]
EditGroups does not rely on MediaWiki tags at all. The only thing that matters is the edit summary: it must conform to the format of the tool you want to attribute the edit to.

**Comment by tfrancart** [comment]
Thanks for clarifying my doubt !
