### ISSUE TITLE
Export batch to CSV

### ISSUE THREAD

**Issue by wetneb** [Wikidata/editgroups#41]
It would help some users to have the possibility to export the list of edits in a batch as a CSV file.

https://www.wikidata.org/wiki/Topic:Wnk9l3fk3kl03lhr

**Comment by derenrich** [comment]
This would be helpful for batch deleting items created in a batch

**Comment by wetneb** [comment]
That is normally supported by the tool itself, if you log into it as an administrator.

**Comment by derenrich** [comment]
oh i wasn't logged in. never mind.
