### ISSUE TITLE
File upload edit groups (Wikimedia Commons) with OpenRefine don't display a summary

### ISSUE THREAD

**Issue by trnstlntk** [Wikidata/editgroups#49]
[Edit groups that concern uploaded files (Wikimedia Commons, using OpenRefine)](https://editgroups-commons.toolforge.org/?tool=OR) mention `(no summary)`, while an edit summary was provided during upload.

![image](https://user-images.githubusercontent.com/9881645/175124225-95d210c4-d48e-4e20-84d7-33478d999f52.png)

**Comment by wetneb** [comment]
Fixed by changing the regex which extracts those summaries
