### ISSUE TITLE
edit group title incorrectly parsed when the summary contains a comma

### ISSUE THREAD

**Issue by maxlath** [Wikidata/editgroups#52]
Example: [here](https://editgroups.toolforge.org/b/wikibase-cli/3da2897c45e4e/) the title is `following the consensus reached in [...]` instead of `removing edition-specific statements from works, following the consensus reached in [...]`

**Comment by wetneb** [comment]
oh hi! :-D
Yes it's annoying. This issue is a duplicate of #4.
If you have any suggestions about how to actually fix it on the EditGroups side (and not expecting tools to replace commas by very similar-looking characters), I am all ears :-D

**Comment by maxlath** [comment]
Hi :D
Hum, I see that that's not exactly trivial, cowardly closing this issue then ^^
