### ISSUE TITLE
Is EditGroup mandatory to Upload edits with OpenRefine?

### ISSUE THREAD

**Issue by JBPressac** [Wikidata/editgroups#53]
Hello,
Is EditGroup mandatory to upload edits on a Wikibase instance? Are they any fields of a manifest for OpenRefine specific to edits uploads ?
Thank you,

**Comment by wetneb** [comment]
Hello,
No it is not required. You can easily disable it by changing the summary prefix in the manifest, removing the link to editgroups.
Editgroups only works with wikibase instances within Wikimedia anyway. I do not know of any tool to mass undo batches of edits in other Wikibase instances.

**Comment by JBPressac** [comment]
Thank you for this answer and for your work on the OpenRefine project
