### ISSUE TITLE
Duration ignores day

### ISSUE THREAD

**Issue by Daniel-Mietchen** [Wikidata/editgroups#7]
Here's what I currently see in https://tools.wmflabs.org/editgroups/b/QSv2T/1535569927362/ :
```
Started | Aug. 29, 2018, 7:12 p.m.
Ended | Aug. 31, 2018, 9:55 p.m.
Duration | 2:43:15
```
This also affects the calculation of the edit speed.

**Comment by wetneb** [comment]
Good catch! Let me fix this.
