### ISSUE TITLE
Undo functionality is broken

### ISSUE THREAD

**Issue by wetneb** [Wikidata/editgroups#89]
Somehow, undoing batches on Wikidata no longer works.
Under the hood, it looks like the reverts are attempted but fail without any logging message.

**Comment by VojtechDostal** [comment]
@wetneb I understand from this that you do not plan to invest your time into this right now? 

Right now, edit groups from the whole last week (last 6 days) do not seem to work. 

As Edit Groups is an essential functionality of Wikidata, without no clear available replacement, maybe this should be reported to WMF? Or is there no maintainer whatsoever right now?

**Comment by wetneb** [comment]
The problem is likely coming from the fact that the redis instance is also used by others and so the communication between the web server and the tasks backend can get some interferences from other users of the redis instance (for instance, some which might take a task from the queue even if it's not intended for them).

The solution would likely be to add a global prefix to all redis keys that we use: it's a feature I requested 6 years ago, it was implemented but I haven't got round to introducing it in EditGroups yet
https://stackoverflow.com/questions/50076885/custom-prefix-for-redis-keys-with-celery

**Comment by wetneb** [comment]
I've spent a bit more time debugging this and trying to fix it, but so far without success. I have written up about the state of the problem in https://phabricator.wikimedia.org/T203557 and https://www.wikidata.org/wiki/Wikidata_talk:Edit_groups#Not_working%3F.

**Comment by wetneb** [comment]
This was solved by switching to a different redis server (see https://www.wikidata.org/wiki/Wikidata_talk:Edit_groups#Not_working%3F)
